name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch: {}

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable
            - name: Update Yarn
              run: |
                  yarn set version 4.1.0
            - name: Setup Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  corepack: true

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run Prettier and ESLint
              run: |
                  yarn lint
                  yarn format

            - name: Run unit tests
              run: yarn test:coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: AverageSoftwareEnjoyer/tune-tools
