name: Lint, format and test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch: {}

jobs:
    lint-and-test:
        timeout-minutes: 60
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable
            - name: Update Yarn
              run: |
                  yarn set version 4.1.1
            - name: Setup Node 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install --immutable

            - name: Run Prettier and ESLint
              run: |
                  yarn lint
                  yarn format

            - name: Run unit tests
              run: yarn test:coverage
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: AverageSoftwareEnjoyer/tune-tools

            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps
            - name: Run e2e tests
              run: yarn e2e
            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
