name: Deploy

on:
    push:
        branches: ["main"]

    workflow_dispatch: {}

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable
            - name: Update Yarn
              run: |
                  yarn set version 4.1.0
            - name: Setup Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  corepack: true

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build the app
              run: yarn build

            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: main
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload source maps to Sentry
              run: |
                  sentry-cli sourcemaps inject /dist
                  sentry-cli sourcemaps upload
