name: Deploy

on:
    push:
        branches: ["main"]

    workflow_dispatch: {}

permissions:
    contents: write
    deployments: write
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup git user
              run: |
                  git config --global user.name ${{ github.actor }}
                  git config --global user.email "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

            - name: Enable Corepack
              run: corepack enable
            - name: Update Yarn
              run: |
                  yarn set version 4.1.0
            - name: Setup Node 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build the app
              run: yarn build --base-href "https://averagesoftwareenjoyer.github.io/tune-tools/"

            - name: Upload source maps to Sentry
              run: yarn sentry:sourcemaps
              env:
                  SENTRY_ORG: tune-tools
                  SENTRY_PROJECT: tune-tools
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

            - name: Deploy
              run: yarn ng deploy

              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
