name: Deploy

on:
    push:
        branches: ["main"]

    workflow_dispatch: {}

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable
            - name: Update Yarn
              run: |
                  yarn set version 4.1.0
            - name: Setup Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  corepack: true

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build the app
              run: yarn build --base-href "https://averagesoftwareenjoyer.github.io/tune-tools/"

            - name: Upload source maps to Sentry
              run: yarn sentry:sourcemaps
              env:
                  SENTRY_ORG: tune-tools
                  SENTRY_PROJECT: tune-tools
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

            - name: Deploy
              run: npx angular-cli-ghpages --base-href="/tune-tools/"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
